src/Entity/Credit.php
<?php

namespace App\Entity;

use App\Repository\CreditRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CreditRepository::class)]
class Credit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $montant = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $taux = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $assurance = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $premiere_echeance = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0)]
    private ?string $duree = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getTaux(): ?string
    {
        return $this->taux;
    }

    public function setTaux(string $taux): static
    {
        $this->taux = $taux;

        return $this;
    }

    public function getAssurance(): ?string
    {
        return $this->assurance;
    }

    public function setAssurance(string $assurance): static
    {
        $this->assurance = $assurance;

        return $this;
    }

    public function getPremiereEcheance(): ?\DateTimeInterface
    {
        return $this->premiere_echeance;
    }

    public function setPremiereEcheance(\DateTimeInterface $premiere_echeance): static
    {
        $this->premiere_echeance = $premiere_echeance;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(string $duree): static
    {
        $this->duree = $duree;

        return $this;
    }
}

src/Form/CreditType.php
<?php

namespace App\Form;

use App\Entity\Credit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CreditType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('montant')
            ->add('taux')
            ->add('assurance')
            ->add('premiere_echeance', null, [
                'widget' => 'single_text',
            ])
            ->add('duree')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Credit::class,
        ]);
    }
}

src/Controller/CreditController.php
<?php

namespace App\Controller;

use App\Entity\Credit;
use App\Entity\Amortissement;
use App\Form\AmortissementType;
use App\Repository\AmortissementRepository;
use App\Form\CreditType;
use App\Repository\CreditRepository;
use App\Repository\PatrimoineRepository;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Service\AmortissementService;

final class CreditController extends AbstractController
{
    /**
     * @var LoggerInterface
     */
    private LoggerInterface $logger;


    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }   

    #[Route('/credit', name: 'credit.index')]
    public function index(CreditRepository $repository): Response
    {
        $credit = $repository->findAll();
        return $this->render('credit/index.html.twig', [
            'credit' => $credit,
        ]);
    }
    #[Route('/credit/show/{id}', name: 'credit.show', methods: ['GET'])]
    public function show(CreditRepository $repository, int $id): Response
    {
        $credit = $repository->findOneBy(['id' => $id]);
        return $this->render('credit/show.html.twig', [
            'credit' => $credit
        ]);
    }
    #[Route('/credit/create', name: 'credit.create', methods: ['GET', 'POST'])]
    public function create(Request $request, EntityManagerInterface $entityManager, AmortissementService $amortissementService): Response
    {
        $credit = new Credit();
        $form = $this->createForm(CreditType::class, $credit);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            
           // try {
            $credit = $form->getData();
            $entityManager->persist($credit);
            // Gérer l'amortissement ici
            $entityManager->flush();
            
            $amortissementService->createAmortissement($credit->getId());

            

           // } catch (Exception $exception) {
             //   $entityManager->rollback();
               // $this->logger->error("L'ajout de l'amortissement a échoué");
            //}
            return $this->redirectToRoute('amortissement.index', ['id' => $credit->getId()]);
        }
        return $this->render('credit/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    #[Route('/credit/edit/{id}', name: 'credit.edit', methods: ['GET', 'POST'])]
    public function edit(PatrimoineRepository $patrimoine, int $id, Request $request, EntityManagerInterface $entityManager): Response
    {
        $credit = $patrimoine->findOneBy(['id' => $id]);
        $form = $this->createForm(CreditType::class, $credit);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $credit = $form->getData();
            $entityManager->flush();
            return $this->redirectToRoute('credit.index');
        }
        return $this->render('credit/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }
    #[Route('/credit/delete/{id}', name: 'credit.delete')]
    public function delete(int $id, CreditRepository $repository, EntityManagerInterface $entityManager): Response
    {
        $credit = $repository->findOneBy(['id' => $id]);
        $entityManager->remove($credit);
        $entityManager->flush();
        return $this->redirectToRoute('credit.index');
    }
}

templates/credit/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CreditController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 1200px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bienvenue dans la création d'un nouveau crédit</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Taux (en %)</th>
                <th scope="col">Assurance (en €)</th>
                <th scope="col">Date de première échéance</th>
                <th scope="col">Montant (en €)</th>
                <th scope="col">Durée (en mois)</th>
                <th scope="col">Créer</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {{ form_start(form) }}
                    <td>{{ form_row(form.taux) }}</td>
                    <td>{{ form_row(form.assurance) }}</td>
                    <td>{{ form_row(form.premiere_echeance) }}</td>
                    <td>{{ form_row(form.montant) }}</td>
                    <td>{{ form_row(form.duree) }}</td>
                    <td><button type="submit" class="btn btn-secondary">Créer</button></td>
                {{ form_end(form) }}
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/credit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CreditController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 1200px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    <h1>Bienvenue dans la modification d'un crédit</h1>

    <table class="table">

        <thead>

            <tr>
                <th scope="col">Taux (en %)</th>
                <th scope="col">Assurance (en €)</th>
                <th scope="col">Date de première échéance</th>
                <th scope="col">Montant (en €)</th>
                <th scope="col">Durée (en mois)</th>
            </tr>

        </thead>

        <tbody>

            <tr>

                {{ form_start(form) }}
                <td>{{ form_row(form.taux) }}</td>
                <td>{{ form_row(form.assurance) }}</td>
                <td>{{ form_row(form.premiere_echeance) }}</td>
                <td>{{ form_row(form.montant) }}</td>
                <td>{{ form_row(form.duree) }}</td>
                <td><button type="submit" class="btn btn-primary">Modifier</button></td>
                {{ form_end(form) }}
            </tr>

        </tbody>

    </table>

</div>

{% endblock %}

templates/credit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CreditController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 1200px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bienvenue dans la gestion de vos crédits</h1>

    <a href="{{ path('credit.create') }}" class="btn btn-success">Ajouter un crédit</a>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Numéro de crédit</th>
                <th scope="col">Taux</th>
                <th scope="col">Assurance</th>
                <th scope="col">Date de première échéance</th>
                <th scope="col">Durée</th>
                <th scope="col">Montant</th>
                <th scope="col">Modifier</th>
                <th scope="col">Supprimer</th>
            </tr>
        </thead>
        <tbody>
            {% for credits in credit %}
                <tr>
                    <td><a href ="{{ path ('credit.show', {id: credits.id})}}">{{ credits.id }}</a></td>
                    <td>{{ credits.taux }} %</td>
                    <td>{{ credits.assurance }} €</td>
                    <td>{{ credits.premiereEcheance|date('d/m/Y') }}</td>
                    <td>{{ credits.duree }} mois</td>
                    <td>{{ credits.montant }} {% if credits.montant>0 %} € {% endif %}</td>
                    <td>
                        <a href="{{ path('credit.edit', {'id': credits.id}) }}" class="btn btn-primary">Modifier</a>
                    </td>
                    <td>
                        <a href="{{ path('credit.delete', {'id': credits.id}) }}" class="btn btn-danger">Supprimer</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">Pas de crédit trouvé.</td>
                </tr>
            {% endfor %}

        </tbody>
</div>
{% endblock %}

templates/credit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CreditController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 1200px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    <h1>Détail du crédit :</h1>

    <h2>Crédit n°{{ credit.id }}</h2>
    <br />
    <p>Taux : {{ credit.taux }} %</p>
    <br />
    <p>Assurance : {{ credit.assurance }} €</p>
    <br />
    <p>Date de première échéance : {{ credit.premiereEcheance|date('d/m/Y') }}</p>
    <br />
    <p>Montant : {{ credit.montant }} {% if credit.montant>0 %} € {% endif %}</p>
    <br />
    <p>Durée : {{ credit.duree }} mois</p>
    <br />

    <button type="button" class="btn btn-info">
        <a href="{{ path ('credit.index')}}">Retour à la liste des crédits</a>
    </button>
    <button type="button" class="btn btn-warning">
        <a href="{{ path ('amortissement.index', {'id': credit.id}) }}">Voir l'amortissement</a>
    </button>
    <button type="button" class="btn btn-danger">
        <a href="{{ path ('credit.delete', {'id': credit.id}) }}">Supprimer</a>
    </button>
    <button type="button" class="btn btn-primary">
        <a href="{{ path ('credit.edit', {'id': credit.id}) }}">Modifier</a>
    </button>

</div>

{% endblock %}